version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  chatbot_pdf:
    build:
      context: .
    container_name: chatbot_pdf
    ports:
      - "7860:7860"
    depends_on:
      - ollama
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py

volumes:
  ollama_data:
